/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Cliente;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author Rafael
 */
public class ClienteEditView extends javax.swing.JDialog {

    /**
     * Creates new form ClienteEditView
     */
    public ClienteEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        NomeLabel = new javax.swing.JLabel();
        NascimentoLabel = new javax.swing.JLabel();
        RgLabel = new javax.swing.JLabel();
        CpfLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        RendaLabel = new javax.swing.JLabel();
        ReferenciaLabel = new javax.swing.JLabel();
        TelRefeLabel = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        RgField = new javax.swing.JTextField();
        CpfField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        RendaField = new javax.swing.JTextField();
        ReferenciaField = new javax.swing.JTextField();
        TelRefeField = new javax.swing.JTextField();
        NascimentoField = new com.toedter.calendar.JDateChooser();
        ConfirmarClienteButton = new javax.swing.JButton();
        CancelarClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NomeLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        NomeLabel.setText("Nome:");

        NascimentoLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        NascimentoLabel.setText("Data de Nascimento:");

        RgLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        RgLabel.setText("RG:");

        CpfLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CpfLabel.setText("CPF:");

        EmailLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        EmailLabel.setText("E-Mail:");

        RendaLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        RendaLabel.setText("Renda:");

        ReferenciaLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ReferenciaLabel.setText("Referência:");

        TelRefeLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        TelRefeLabel.setText("Telefone de referência:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.nome}"), NomeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.rg}"), RgField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.cpf}"), CpfField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.email}"), EmailField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.renda}"), RendaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.referencia}"), ReferenciaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.foneReferencia}"), TelRefeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtualCliente.dtNasc}"), NascimentoField, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        ConfirmarClienteButton.setText("Confirmar");
        ConfirmarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarClienteButtonActionPerformed(evt);
                salvarNovoCliente(evt);
            }
        });

        CancelarClienteButton.setText("Cancelar");
        CancelarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RgLabel)
                        .addGap(34, 34, 34)
                        .addComponent(RgField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CpfLabel)
                        .addGap(28, 28, 28)
                        .addComponent(CpfField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailLabel)
                                .addGap(16, 16, 16)
                                .addComponent(EmailField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NascimentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NascimentoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RendaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RendaField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReferenciaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ReferenciaField)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TelRefeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TelRefeField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelarClienteButton)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmarClienteButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NascimentoLabel)
                    .addComponent(NascimentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RgLabel)
                    .addComponent(RgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfLabel)
                    .addComponent(CpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RendaLabel)
                    .addComponent(RendaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReferenciaLabel)
                    .addComponent(ReferenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelRefeLabel)
                    .addComponent(TelRefeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarClienteButton)
                    .addComponent(CancelarClienteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarClienteButtonActionPerformed
         
    }//GEN-LAST:event_ConfirmarClienteButtonActionPerformed

    private void CancelarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarClienteButtonActionPerformed
        setConfirmaCliente(false);
        setVisible(false);
    }//GEN-LAST:event_CancelarClienteButtonActionPerformed

    private void salvarNovoCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarNovoCliente
        setConfirmaCliente(true);
        setVisible(false);
    }//GEN-LAST:event_salvarNovoCliente

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteEditView dialog = new ClienteEditView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarClienteButton;
    private javax.swing.JButton ConfirmarClienteButton;
    private javax.swing.JTextField CpfField;
    private javax.swing.JLabel CpfLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private com.toedter.calendar.JDateChooser NascimentoField;
    private javax.swing.JLabel NascimentoLabel;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField ReferenciaField;
    private javax.swing.JLabel ReferenciaLabel;
    private javax.swing.JTextField RendaField;
    private javax.swing.JLabel RendaLabel;
    private javax.swing.JTextField RgField;
    private javax.swing.JLabel RgLabel;
    private javax.swing.JTextField TelRefeField;
    private javax.swing.JLabel TelRefeLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
        private Cliente registroAtualCliente;

    /**
     * Get the value of registroAtualCliente
     *
     * @return the value of registroAtualCliente
     */
    public Cliente getRegistroAtualCliente() {
        return registroAtualCliente;
    }

    /**
     * Set the value of registroAtualCliente
     *
     * @param registroAtualCliente new value of registroAtualCliente
     */
    public void setRegistroAtualCliente(Cliente registroAtualCliente) {
        Cliente oldCliente = this.registroAtualCliente;      
        this.registroAtualCliente = registroAtualCliente;
        propertyChangeSupport.firePropertyChange("registroAtualCliente", oldCliente, registroAtualCliente);
    }
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }
        private boolean confirmaCliente;

    /**
     * Get the value of confirmaCliente
     *
     * @return the value of confirmaCliente
     */
    public boolean isConfirmaCliente() {
        return confirmaCliente;
    }

    /**
     * Set the value of confirmaCliente
     *
     * @param confirmaCliente new value of confirmaCliente
     */
    public void setConfirmaCliente(boolean confirmaCliente) {
        this.confirmaCliente = confirmaCliente;
    }
}
