/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Rafael
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setExtendedState(Menu.MAXIMIZED_BOTH);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel1 = new javax.swing.JPanel();
        MenuPanel2 = new javax.swing.JPanel();
        MenuToolBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButton11 = new javax.swing.JButton();
        MenuPanel3 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        ClienteMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMIFornecedor = new javax.swing.JMenuItem();
        jMIConta = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIDepartamento = new javax.swing.JMenuItem();
        jMIFuncionarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMICartao = new javax.swing.JMenuItem();
        jMIPlanoConta = new javax.swing.JMenuItem();
        jMITipoPr = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMISair = new javax.swing.JMenuItem();
        jMMovimento = new javax.swing.JMenu();
        jMIContaPagar = new javax.swing.JMenuItem();
        jMIContaReceber = new javax.swing.JMenuItem();
        jMIVenda = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMControleEstoque = new javax.swing.JMenu();
        jMIEntradaNF = new javax.swing.JMenuItem();
        jMIAtualizaPreco = new javax.swing.JMenuItem();
        jMCompras = new javax.swing.JMenu();
        jMIRequisicao = new javax.swing.JMenuItem();
        jMICotacao = new javax.swing.JMenuItem();
        jMIConfCotacao = new javax.swing.JMenuItem();
        jMIPedido = new javax.swing.JMenuItem();
        jMTesouBanco = new javax.swing.JMenu();
        jMIEmiCheque = new javax.swing.JMenuItem();
        jMIConcCheque = new javax.swing.JMenuItem();
        jMIMovBanco = new javax.swing.JMenuItem();
        jMUltilitarios = new javax.swing.JMenu();
        jMICalculadora = new javax.swing.JMenuItem();
        jMICalendario = new javax.swing.JMenuItem();
        TelaCheiaMen = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMSistemaSeguranca = new javax.swing.JMenu();
        jMITrocaSenha = new javax.swing.JMenuItem();
        jMINivelAcesso = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMISobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP - ENTERPRISE RESOURCE PLANNING");
        setIconImages(null);

        MenuPanel2.setBackground(new java.awt.Color(16, 91, 154));

        MenuToolBar.setBackground(new java.awt.Color(16, 91, 154));
        MenuToolBar.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Person-Male-Light-icon-big.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Groups-Meeting-Dark-icon.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Paper-Money-icon-big.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Not-Available-for-Work-icon-big.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/basket-icon-big.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton5);
        MenuToolBar.add(jSeparator7);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/payment-icon-medium.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Payment-Methods-Cash-receiving-icon-big.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Price-icon-big.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton8);
        MenuToolBar.add(jSeparator8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Calculator-icon-big.png"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Calendar-icon-big.png"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(jButton10);
        MenuToolBar.add(jSeparator9);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Windows-Turn-Off-icon-big.png"))); // NOI18N
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        MenuToolBar.add(jButton11);

        javax.swing.GroupLayout MenuPanel2Layout = new javax.swing.GroupLayout(MenuPanel2);
        MenuPanel2.setLayout(MenuPanel2Layout);
        MenuPanel2Layout.setHorizontalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        MenuPanel2Layout.setVerticalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuPanel3Layout = new javax.swing.GroupLayout(MenuPanel3);
        MenuPanel3.setLayout(MenuPanel3Layout);
        MenuPanel3Layout.setHorizontalGroup(
            MenuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuPanel3Layout.setVerticalGroup(
            MenuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuPanel1Layout = new javax.swing.GroupLayout(MenuPanel1);
        MenuPanel1.setLayout(MenuPanel1Layout);
        MenuPanel1Layout.setHorizontalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanel1Layout.setVerticalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuBar.setPreferredSize(new java.awt.Dimension(322, 40));

        ClienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Actions-user-group-new-icon.png"))); // NOI18N
        ClienteMenu.setText("Cadastro     ");
        ClienteMenu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Person-Male-Light-icon.png"))); // NOI18N
        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMenuItem3);

        jMIFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMIFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Groups-Meeting-Light-icon.png"))); // NOI18N
        jMIFornecedor.setMnemonic('F');
        jMIFornecedor.setText("Fornecedores");
        jMIFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFornecedorActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMIFornecedor);

        jMIConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMIConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/shop-cart-icon.png"))); // NOI18N
        jMIConta.setMnemonic('B');
        jMIConta.setText("Contas Bancárias");
        jMIConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIContaActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMIConta);
        ClienteMenu.add(jSeparator4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Not-Available-for-Work-icon.png"))); // NOI18N
        jMenuItem1.setMnemonic('U');
        jMenuItem1.setText("Unidades");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/basket-icon.png"))); // NOI18N
        jMenuItem2.setMnemonic('P');
        jMenuItem2.setText("Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMenuItem2);
        ClienteMenu.add(jSeparator1);

        jMIDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMIDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/callcenter-girls-glasses-icon.png"))); // NOI18N
        jMIDepartamento.setMnemonic('D');
        jMIDepartamento.setText("Departamento");
        jMIDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDepartamentoActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMIDepartamento);

        jMIFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMIFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/User-Files-icon.png"))); // NOI18N
        jMIFuncionarios.setMnemonic('n');
        jMIFuncionarios.setText("Funcionários");
        jMIFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFuncionariosActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMIFuncionarios);
        ClienteMenu.add(jSeparator2);

        jMICartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Credit-Card-icon.png"))); // NOI18N
        jMICartao.setText("Cartões");
        jMICartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICartaoActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMICartao);

        jMIPlanoConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Actions-resource-group-icon.png"))); // NOI18N
        jMIPlanoConta.setText("Plano de Conta");
        jMIPlanoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPlanoContaActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMIPlanoConta);

        jMITipoPr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMITipoPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Invoice-icon.png"))); // NOI18N
        jMITipoPr.setMnemonic('T');
        jMITipoPr.setText("Tipo de Pgto/Rcbto");
        jMITipoPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITipoPrActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMITipoPr);
        ClienteMenu.add(jSeparator3);

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMISair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Windows-Turn-Off-icon.png"))); // NOI18N
        jMISair.setMnemonic('e');
        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        ClienteMenu.add(jMISair);

        jMenuBar.add(ClienteMenu);

        jMMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/circulation-icon.png"))); // NOI18N
        jMMovimento.setText("Movimento    ");
        jMMovimento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMIContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/payment-icon.png"))); // NOI18N
        jMIContaPagar.setText("Contas a Pagar");
        jMMovimento.add(jMIContaPagar);

        jMIContaReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Payment-Methods-Cash-receiving-icon.png"))); // NOI18N
        jMIContaReceber.setText("Contas a Receber");
        jMIContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIContaReceberActionPerformed(evt);
            }
        });
        jMMovimento.add(jMIContaReceber);

        jMIVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMIVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Price-icon.png"))); // NOI18N
        jMIVenda.setMnemonic('V');
        jMIVenda.setText("Vendas");
        jMIVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVendaActionPerformed(evt);
            }
        });
        jMMovimento.add(jMIVenda);
        jMMovimento.add(jSeparator5);

        jMControleEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Cabinet-icon.png"))); // NOI18N
        jMControleEstoque.setText("Controle de Estoque");

        jMIEntradaNF.setText("Entrada de NF");
        jMControleEstoque.add(jMIEntradaNF);

        jMIAtualizaPreco.setText("Atualização de Preços");
        jMControleEstoque.add(jMIAtualizaPreco);

        jMMovimento.add(jMControleEstoque);

        jMCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/money-icon.png"))); // NOI18N
        jMCompras.setText("Compras");

        jMIRequisicao.setText("Requisição");
        jMCompras.add(jMIRequisicao);

        jMICotacao.setText("Cotação");
        jMCompras.add(jMICotacao);

        jMIConfCotacao.setText("Confirma Cotação");
        jMCompras.add(jMIConfCotacao);

        jMIPedido.setText("Pedido");
        jMCompras.add(jMIPedido);

        jMMovimento.add(jMCompras);

        jMTesouBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dollar-icon.png"))); // NOI18N
        jMTesouBanco.setText("Tesouraria e Banco");

        jMIEmiCheque.setText("Emissão de Cheques");
        jMTesouBanco.add(jMIEmiCheque);

        jMIConcCheque.setText("Conciliação de Cheques");
        jMIConcCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConcChequeActionPerformed(evt);
            }
        });
        jMTesouBanco.add(jMIConcCheque);

        jMIMovBanco.setText("Movimento de Banco");
        jMTesouBanco.add(jMIMovBanco);

        jMMovimento.add(jMTesouBanco);

        jMenuBar.add(jMMovimento);

        jMUltilitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/3D-objects-icon.png"))); // NOI18N
        jMUltilitarios.setText("Ultilitários    ");
        jMUltilitarios.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMICalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Calculator-icon.png"))); // NOI18N
        jMICalculadora.setText("Calculadora");
        jMICalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICalculadoraActionPerformed(evt);
            }
        });
        jMUltilitarios.add(jMICalculadora);

        jMICalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Calendar-icon.png"))); // NOI18N
        jMICalendario.setText("Calendário");
        jMUltilitarios.add(jMICalendario);

        TelaCheiaMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        TelaCheiaMen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/App-randr-icon.png"))); // NOI18N
        TelaCheiaMen.setText("Tela Cheia");
        TelaCheiaMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaCheiaMenActionPerformed(evt);
            }
        });
        jMUltilitarios.add(TelaCheiaMen);
        jMUltilitarios.add(jSeparator6);

        jMSistemaSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Misc-Security-icon.png"))); // NOI18N
        jMSistemaSeguranca.setText("Sistema de Segurança");

        jMITrocaSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMITrocaSenha.setText("Trocar senha Corrente");
        jMSistemaSeguranca.add(jMITrocaSenha);

        jMINivelAcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMINivelAcesso.setText("Definir Nível de Acesso");
        jMINivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINivelAcessoActionPerformed(evt);
            }
        });
        jMSistemaSeguranca.add(jMINivelAcesso);

        jMUltilitarios.add(jMSistemaSeguranca);

        jMenuBar.add(jMUltilitarios);

        jMAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Adobe-Help-Center-icon.png"))); // NOI18N
        jMAjuda.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMAjuda.setLabel("Ajuda");

        jMISobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/about-icon.png"))); // NOI18N
        jMISobre.setText("Sobre o Sistema");
        jMISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISobreActionPerformed(evt);
            }
        });
        jMAjuda.add(jMISobre);

        jMenuBar.add(jMAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jMIConta.doClick();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMISobreActionPerformed

    private void jMINivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMINivelAcessoActionPerformed

    private void jMICalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICalculadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICalculadoraActionPerformed

    private void jMIConcChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConcChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIConcChequeActionPerformed

    private void jMIContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIContaReceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIContaReceberActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMITipoPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITipoPrActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Tipo de Pagamentos e Recebimentos";
        TipoPagamentoView.main(args);
    }//GEN-LAST:event_jMITipoPrActionPerformed

    private void jMIPlanoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPlanoContaActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Plano de Contas";
        PlanoContaView.main(args);
    }//GEN-LAST:event_jMIPlanoContaActionPerformed

    private void jMICartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICartaoActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Cartões";
        CartaoView.main(args);
    }//GEN-LAST:event_jMICartaoActionPerformed

    private void jMIFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFuncionariosActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Funcionários";
        FuncionarioView.main(args);
    }//GEN-LAST:event_jMIFuncionariosActionPerformed

    private void jMIContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIContaActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro das Contas Bancárias";
        BancoView.main(args);
    }//GEN-LAST:event_jMIContaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jMenuItem3.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Cliente";
        ClienteView.main(args);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMIFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFornecedorActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Fronecedores";
        FornecedorView.main(args);
    }//GEN-LAST:event_jMIFornecedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jMIFornecedor.doClick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Produtos";
        ProdutoView.main(args);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jMenuItem2.doClick();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jMenuItem1.doClick();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Unidades";
        UnidadeView.main(args);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMIDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDepartamentoActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Departamentos";
        DepartamentoView.main(args);
    }//GEN-LAST:event_jMIDepartamentoActionPerformed

    private void TelaCheiaMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaCheiaMenActionPerformed
        if(controlador ==  0) {
            GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            gd.setFullScreenWindow(this);
            controlador = 1;
        }else if(controlador == 1) {
            GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            gd.setFullScreenWindow(null);
            controlador = 0;
        }
    }//GEN-LAST:event_TelaCheiaMenActionPerformed

    private void jMIVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVendaActionPerformed
        String args[] = new String[1];
        args[0] = "Movimento - Vendas";
        MovimentoVenda.main(args);
    }//GEN-LAST:event_jMIVendaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jMIVenda.doClick();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private int controlador = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ClienteMenu;
    private javax.swing.JPanel MenuPanel1;
    private javax.swing.JPanel MenuPanel2;
    private javax.swing.JPanel MenuPanel3;
    private javax.swing.JToolBar MenuToolBar;
    private javax.swing.JMenuItem TelaCheiaMen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenu jMCompras;
    private javax.swing.JMenu jMControleEstoque;
    private javax.swing.JMenuItem jMIAtualizaPreco;
    private javax.swing.JMenuItem jMICalculadora;
    private javax.swing.JMenuItem jMICalendario;
    private javax.swing.JMenuItem jMICartao;
    private javax.swing.JMenuItem jMIConcCheque;
    private javax.swing.JMenuItem jMIConfCotacao;
    private javax.swing.JMenuItem jMIConta;
    private javax.swing.JMenuItem jMIContaPagar;
    private javax.swing.JMenuItem jMIContaReceber;
    private javax.swing.JMenuItem jMICotacao;
    private javax.swing.JMenuItem jMIDepartamento;
    private javax.swing.JMenuItem jMIEmiCheque;
    private javax.swing.JMenuItem jMIEntradaNF;
    private javax.swing.JMenuItem jMIFornecedor;
    private javax.swing.JMenuItem jMIFuncionarios;
    private javax.swing.JMenuItem jMIMovBanco;
    private javax.swing.JMenuItem jMINivelAcesso;
    private javax.swing.JMenuItem jMIPedido;
    private javax.swing.JMenuItem jMIPlanoConta;
    private javax.swing.JMenuItem jMIRequisicao;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenuItem jMITipoPr;
    private javax.swing.JMenuItem jMITrocaSenha;
    private javax.swing.JMenuItem jMIVenda;
    private javax.swing.JMenu jMMovimento;
    private javax.swing.JMenu jMSistemaSeguranca;
    private javax.swing.JMenu jMTesouBanco;
    private javax.swing.JMenu jMUltilitarios;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
